### ISSUE TITLE
Find replacement for cornercouch or fork it

### ISSUE THREAD

**Issue by bitsandbytes** [mobdata/replication#20]
The cornercouch.js project hasn't been updated in a couple years and is now using deprecated angular functions. 

But couchapp is a useful tool and made making "monitor" pretty easy.

Look into cornercouch forks, see if anyone has updated. Look into other ways to use angular in couchapp and determine if cornercouch has advantages over other ways. 

Here's the original cornercouch repo:
https://github.com/eddelplus/CornerCouch

Here's how one person imported the underscore lib into couchdb using the commonjs module method:
http://www.swarmforest.com/blog/how-to-use-js-libs-like-underscorejs-in-your-couchdb-views/

FYI: The current "monitor" app defines a simple commonjs module in views/lib/security.js and references it in validate_doc_update.

The current "monitor" app also has edits to the original cornercouch.js. See the use of successCallback() and errorCallback() in the CouchServer.prototype.login function.

The updates I made to cornercouch.js are simple, so we could simply fork it ourselves and make the updates. If there's someone else actively maintaining cornercouch I'd rather go with that.

This ticket is done when you've either:
* Forked cornercouch into mobdata, applied the changes I made.
* Decided to use something other than the current cornercouch.
* Demonstrated that the LOE for any of this isn't worth it.

**Comment by rudyj03** [comment]
It seems the deprecated methods (the .success and .error promises on the $http service) were deprecated as of August 2015.  So I haven't had much luck in finding a library that doesn't use those methods.  The other angular-ready library is https://github.com/IvoNet/angular-ivonet-couchdb, but it too uses those deprecated methods.

One option is to use the couch.js wrapper that comes with CouchDB (can be seen at _utils/script/couch.js).  This is a simple wrapper that does everything we need it to, and it already ships with CouchDB.  I'm not quite sure just yet how to incorporate this into Angular, but it might be an ideal way to go forward.
