### ISSUE TITLE
(Parent #232) Build rpm to prep for nodejs

### ISSUE THREAD

**Issue by bitsandbytes** [mobdata/replication#236]
Prereqs: #234, #235

Since nodejs 6 LTS isn't available in CentOs's v6 yum repos the expectation is that installing it from a yum repo (see #233) may work but if there is any configuration needed _before_ installing it we will want to put our changes into an rpm.

The goal is to prepare our VM's to install a "vanilla" build of node.js. This new rpm will not install modules like react nor setup any mobdata webapps.

What to do:
* In the "build" repo, add a directory called `nodejs-init` or `nodejs-prep`, or something like that.
* Put the rpm's spec file and any additional files in this new directory.
* In the "build" repo, you should be able to run `./build-rpm.sh nodejs-init` and if it runs without error then you have an rpm ready to test.
* Once the rpm is working, copy it to `/opt/update_yum_repo/rpms/`

**Comment by dbk91** [comment]
RPM was pulled down from https://rpm.nodesource.com/pub_6.x/el/6/x86_64/; utilizing nodejs-6.10.0-1nodesource.el6.x86_64.rpm
