### ISSUE TITLE
Reloading repmon webpage shows empty login form for a  moment

### ISSUE THREAD

**Issue by bitsandbytes** [mobdata/replication#62]
Log into repmon then refresh the page. The login form is shown for a moment then it's replaced by the normal app (active tasks and other grids).

The issue is that the page loads before the session is tested to see if it's still a valid session. Update this so that the page first validates the session and then goes to the proper content from there.

**Comment by rudyj03** [comment]
Added a boolean that only gets set after the session is checked, even if the session check fails.
