### ISSUE TITLE
Style loginmodal. Make it real.

### ISSUE THREAD

**Issue by bitsandbytes** [mobdata/replication#75]
The loginModal uses login/login.template.html. The background to the modal is clear. Rather than appearing as a pop-up it appears as 3 items (username, password, submit) just floating in space.

What to do:
* Update the login.template.html file to have a background.
* The size of the login form, once it has a visible background, is left up to the implementer.
  * Whether it's a pop-up or 
  * Takes up the entire browser viewable area is up to you.

**Comment by rudyj03** [comment]
The login modal is no longer dismissible by clicking away or pushing the escape key.  If we want to change this, it's just a matter of removing the backdrop and keyboard options passed to the login modal open function.
